name: Robot Framework Reporter Demo

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  format-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensures history is available for commits, necessary for pushes

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install robotidy
        run: pip install robotidy

      - name: Run formatting script
        run: |
          chmod +x format_project.sh
          ./format_codebase.sh

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git diff --staged --quiet || git commit -m "Apply robotidy formatting"
          git push origin HEAD:${{ github.head_ref }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_tests_dir: tests
      - name: Store test report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: reports

  generate_report:
    if: always()
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: reports
      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.3
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
#    format:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install robotframework-tidy
#         run: |
#           pip install robotframework-tidy
#           ./format.sh

# report:
# if: always()
#   needs: [test]
#   runs-on: ubuntu-latest
#   steps:
#   - uses: actions/checkout@v2
#   - name: Download test report
#     uses: actions/download-artifact@v1
#     with:
#       name: reports
#   - name: Output report
#     uses: joonvena/robotframework-reporter-action@v2
# with:
#   gh_access_token: ${{ secrets.GITHUB_TOKEN }}
